#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

ENV_FILE="${ROOT_DIR}/.server_env"
DEFAULT_NEIGHBOR_URL="http://111.230.32.219:8000"

DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-dllm-server:latest}"
DOCKER_CONTAINER_NAME="${DOCKER_CONTAINER_NAME:-dllm-server}"
DOCKER_WEB_CONTAINER_NAME="${DOCKER_WEB_CONTAINER_NAME:-dllm-web}"
DLLM_SERVER_PORT="${DLLM_SERVER_PORT:-8000}"
DLLM_WEB_PORT="${DLLM_WEB_PORT:-5173}"
DLLM_SERVER_DB_URL="${DLLM_SERVER_DB_URL:-sqlite:///./data/server.db}"
DLLM_SERVER_API_KEYS_BOOTSTRAP="${DLLM_SERVER_API_KEYS_BOOTSTRAP:-dev-key-123}"
DLLM_SERVER_CLUSTER_ENABLED="${DLLM_SERVER_CLUSTER_ENABLED:-true}"
VITE_API_KEY="${VITE_API_KEY:-dev-key-123}"
VITE_USE_MOCK="${VITE_USE_MOCK:-false}"

if [ -f "${ENV_FILE}" ]; then
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
fi

NODE_IP="${NODE_IP:-127.0.0.1}"
NODE_INTERNAL_IP="${NODE_INTERNAL_IP:-127.0.0.1}"
DLLM_SERVER_CLUSTER_SELF_URL="http://${NODE_IP}:${DLLM_SERVER_PORT}"
VITE_API_BASE="${VITE_API_BASE:-http://${NODE_IP}:${DLLM_SERVER_PORT}}"
DLLM_SERVER_CORS_ALLOW_ORIGINS="http://${NODE_IP}:${DLLM_WEB_PORT},http://${NODE_INTERNAL_IP}:${DLLM_WEB_PORT},http://127.0.0.1:${DLLM_WEB_PORT},http://localhost:${DLLM_WEB_PORT}"
DLLM_SERVER_CORS_ALLOW_CREDENTIALS="${DLLM_SERVER_CORS_ALLOW_CREDENTIALS:-false}"

if [ -n "${DLLM_SERVER_INTERNAL_TOKEN:-}" ]; then
  INTERNAL_TOKEN="${DLLM_SERVER_INTERNAL_TOKEN}"
else
  INTERNAL_TOKEN="$(openssl rand -hex 24)"
fi

NODE_ID="node-$(date +%Y%m%d%H%M%S)-$(openssl rand -hex 4)"

CURRENT_SEEDS="${DLLM_SERVER_CLUSTER_SEED_URLS:-}"
if [ -n "${CURRENT_SEEDS}" ]; then
  DLLM_SERVER_CLUSTER_SEED_URLS="${DEFAULT_NEIGHBOR_URL},${CURRENT_SEEDS}"
else
  DLLM_SERVER_CLUSTER_SEED_URLS="${DEFAULT_NEIGHBOR_URL}"
fi

# Deduplicate seed URLs while preserving order.
DLLM_SERVER_CLUSTER_SEED_URLS="$(echo "${DLLM_SERVER_CLUSTER_SEED_URLS}" | tr ',' '\n' | awk 'NF && !x[$0]++' | paste -sd ',' -)"

cat > "${ENV_FILE}" <<EOF
DLLM_SERVER_DB_URL=${DLLM_SERVER_DB_URL}
DLLM_SERVER_API_KEYS_BOOTSTRAP=${DLLM_SERVER_API_KEYS_BOOTSTRAP}
DLLM_SERVER_INTERNAL_TOKEN=${INTERNAL_TOKEN}
DLLM_SERVER_CLUSTER_ENABLED=${DLLM_SERVER_CLUSTER_ENABLED}
DLLM_SERVER_CLUSTER_NODE_ID=${NODE_ID}
DLLM_SERVER_CLUSTER_SELF_URL=${DLLM_SERVER_CLUSTER_SELF_URL}
DLLM_SERVER_CLUSTER_SEED_URLS=${DLLM_SERVER_CLUSTER_SEED_URLS}
DLLM_SERVER_CORS_ALLOW_ORIGINS=${DLLM_SERVER_CORS_ALLOW_ORIGINS}
DLLM_SERVER_CORS_ALLOW_CREDENTIALS=${DLLM_SERVER_CORS_ALLOW_CREDENTIALS}
DLLM_SERVER_PORT=${DLLM_SERVER_PORT}
NODE_IP=${NODE_IP}
NODE_INTERNAL_IP=${NODE_INTERNAL_IP}
DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}
DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}
DOCKER_WEB_CONTAINER_NAME=${DOCKER_WEB_CONTAINER_NAME}
DLLM_WEB_PORT=${DLLM_WEB_PORT}
VITE_API_BASE=${VITE_API_BASE}
VITE_API_KEY=${VITE_API_KEY}
VITE_USE_MOCK=${VITE_USE_MOCK}
EOF

mkdir -p "${ROOT_DIR}/data/server"

if docker compose version >/dev/null 2>&1; then
  docker compose --env-file "${ENV_FILE}" -f docker-compose.server.yml up -d --build
else
  docker-compose --env-file "${ENV_FILE}" -f docker-compose.server.yml up -d --build
fi

echo "Deploy complete."
echo "Node ID: ${NODE_ID}"
echo "Internal token persisted at ${ENV_FILE}"
