#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

ENV_FILE="${ROOT_DIR}/.server_env"
DEFAULT_NEIGHBOR_URL="http://111.230.32.219:8000"

ORIG_DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME-}"
ORIG_DOCKER_CONTAINER_NAME="${DOCKER_CONTAINER_NAME-}"
ORIG_DOCKER_WEB_CONTAINER_NAME="${DOCKER_WEB_CONTAINER_NAME-}"
ORIG_DLLM_SERVER_PORT="${DLLM_SERVER_PORT-}"
ORIG_DLLM_WEB_PORT="${DLLM_WEB_PORT-}"
ORIG_DLLM_SERVER_DB_URL="${DLLM_SERVER_DB_URL-}"
ORIG_DLLM_SERVER_API_KEYS_BOOTSTRAP="${DLLM_SERVER_API_KEYS_BOOTSTRAP-}"
ORIG_DLLM_SERVER_CLUSTER_ENABLED="${DLLM_SERVER_CLUSTER_ENABLED-}"
ORIG_VITE_API_KEY="${VITE_API_KEY-}"
ORIG_VITE_USE_MOCK="${VITE_USE_MOCK-}"
ORIG_NODE_IP="${NODE_IP-}"
ORIG_NODE_INTERNAL_IP="${NODE_INTERNAL_IP-}"
ORIG_VITE_API_BASE="${VITE_API_BASE-}"
ORIG_VITE_PROXY_TARGET="${VITE_PROXY_TARGET-}"
ORIG_DLLM_SERVER_CORS_ALLOW_ORIGINS="${DLLM_SERVER_CORS_ALLOW_ORIGINS-}"
ORIG_DLLM_SERVER_CORS_ALLOW_CREDENTIALS="${DLLM_SERVER_CORS_ALLOW_CREDENTIALS-}"
ORIG_DLLM_SERVER_INTERNAL_TOKEN="${DLLM_SERVER_INTERNAL_TOKEN-}"
ORIG_DLLM_SERVER_CLUSTER_SEED_URLS="${DLLM_SERVER_CLUSTER_SEED_URLS-}"
ORIG_DLLM_SERVER_DISPATCH_INTERVAL_SEC="${DLLM_SERVER_DISPATCH_INTERVAL_SEC-}"
ORIG_DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO="${DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO-}"

if [ -f "${ENV_FILE}" ]; then
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
fi

choose_value() {
  local original="$1"
  local existing="$2"
  local fallback="$3"
  if [ -n "${original}" ]; then
    printf '%s' "${original}"
  elif [ -n "${existing}" ]; then
    printf '%s' "${existing}"
  else
    printf '%s' "${fallback}"
  fi
}

normalize_csv() {
  local raw="$1"
  printf '%s' "${raw}" | tr '，' ',' | sed -E 's/[[:space:]]*,[[:space:]]*/,/g; s/^[[:space:]]+//; s/[[:space:]]+$//'
}

DOCKER_IMAGE_NAME="$(choose_value "${ORIG_DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_NAME-}" "dllm-server:latest")"
DOCKER_CONTAINER_NAME="$(choose_value "${ORIG_DOCKER_CONTAINER_NAME}" "${DOCKER_CONTAINER_NAME-}" "dllm-server")"
DOCKER_WEB_CONTAINER_NAME="$(choose_value "${ORIG_DOCKER_WEB_CONTAINER_NAME}" "${DOCKER_WEB_CONTAINER_NAME-}" "dllm-web")"
DLLM_SERVER_PORT="$(choose_value "${ORIG_DLLM_SERVER_PORT}" "${DLLM_SERVER_PORT-}" "8000")"
DLLM_WEB_PORT="$(choose_value "${ORIG_DLLM_WEB_PORT}" "${DLLM_WEB_PORT-}" "5173")"
DLLM_SERVER_DB_URL="$(choose_value "${ORIG_DLLM_SERVER_DB_URL}" "${DLLM_SERVER_DB_URL-}" "sqlite:///./data/server.db")"
DLLM_SERVER_API_KEYS_BOOTSTRAP="$(choose_value "${ORIG_DLLM_SERVER_API_KEYS_BOOTSTRAP}" "${DLLM_SERVER_API_KEYS_BOOTSTRAP-}" "dev-key-123")"
DLLM_SERVER_API_KEYS_BOOTSTRAP="$(normalize_csv "${DLLM_SERVER_API_KEYS_BOOTSTRAP}")"
DLLM_SERVER_CLUSTER_ENABLED="$(choose_value "${ORIG_DLLM_SERVER_CLUSTER_ENABLED}" "${DLLM_SERVER_CLUSTER_ENABLED-}" "true")"
VITE_API_KEY="$(choose_value "${ORIG_VITE_API_KEY}" "${VITE_API_KEY-}" "dev-key-123")"
VITE_USE_MOCK="$(choose_value "${ORIG_VITE_USE_MOCK}" "${VITE_USE_MOCK-}" "false")"

NODE_IP="$(choose_value "${ORIG_NODE_IP}" "${NODE_IP-}" "127.0.0.1")"
NODE_INTERNAL_IP="$(choose_value "${ORIG_NODE_INTERNAL_IP}" "${NODE_INTERNAL_IP-}" "127.0.0.1")"
DLLM_SERVER_CLUSTER_SELF_URL="http://${NODE_IP}:${DLLM_SERVER_PORT}"
VITE_API_BASE="$(choose_value "${ORIG_VITE_API_BASE}" "${VITE_API_BASE-}" "/api")"
VITE_PROXY_TARGET="$(choose_value "${ORIG_VITE_PROXY_TARGET}" "${VITE_PROXY_TARGET-}" "http://dllm-server:8000")"
DLLM_SERVER_CORS_ALLOW_ORIGINS="$(choose_value "${ORIG_DLLM_SERVER_CORS_ALLOW_ORIGINS}" "${DLLM_SERVER_CORS_ALLOW_ORIGINS-}" "http://${NODE_INTERNAL_IP}:${DLLM_WEB_PORT},http://127.0.0.1:${DLLM_WEB_PORT},http://localhost:${DLLM_WEB_PORT}")"
DLLM_SERVER_CORS_ALLOW_CREDENTIALS="$(choose_value "${ORIG_DLLM_SERVER_CORS_ALLOW_CREDENTIALS}" "${DLLM_SERVER_CORS_ALLOW_CREDENTIALS-}" "false")"
DLLM_SERVER_DISPATCH_INTERVAL_SEC="$(choose_value "${ORIG_DLLM_SERVER_DISPATCH_INTERVAL_SEC}" "${DLLM_SERVER_DISPATCH_INTERVAL_SEC-}" "2.0")"
DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO="$(choose_value "${ORIG_DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO}" "${DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO-}" "0.1")"

if [ -n "${ORIG_DLLM_SERVER_INTERNAL_TOKEN}" ]; then
  INTERNAL_TOKEN="${ORIG_DLLM_SERVER_INTERNAL_TOKEN}"
elif [ -n "${DLLM_SERVER_INTERNAL_TOKEN:-}" ]; then
  INTERNAL_TOKEN="${DLLM_SERVER_INTERNAL_TOKEN}"
else
  INTERNAL_TOKEN="$(openssl rand -hex 24)"
fi

NODE_ID="node-$(date +%Y%m%d%H%M%S)-$(openssl rand -hex 4)"

CURRENT_SEEDS="$(choose_value "${ORIG_DLLM_SERVER_CLUSTER_SEED_URLS}" "${DLLM_SERVER_CLUSTER_SEED_URLS-}" "")"
if [ -n "${CURRENT_SEEDS}" ]; then
  DLLM_SERVER_CLUSTER_SEED_URLS="${DEFAULT_NEIGHBOR_URL},${CURRENT_SEEDS}"
else
  DLLM_SERVER_CLUSTER_SEED_URLS="${DEFAULT_NEIGHBOR_URL}"
fi

# Deduplicate seed URLs while preserving order.
DLLM_SERVER_CLUSTER_SEED_URLS="$(echo "${DLLM_SERVER_CLUSTER_SEED_URLS}" | tr ',' '\n' | awk 'NF && !x[$0]++' | paste -sd ',' -)"

cat > "${ENV_FILE}" <<EOF
DLLM_SERVER_DB_URL=${DLLM_SERVER_DB_URL}
DLLM_SERVER_API_KEYS_BOOTSTRAP=${DLLM_SERVER_API_KEYS_BOOTSTRAP}
DLLM_SERVER_INTERNAL_TOKEN=${INTERNAL_TOKEN}
DLLM_SERVER_CLUSTER_ENABLED=${DLLM_SERVER_CLUSTER_ENABLED}
DLLM_SERVER_CLUSTER_NODE_ID=${NODE_ID}
DLLM_SERVER_CLUSTER_SELF_URL=${DLLM_SERVER_CLUSTER_SELF_URL}
DLLM_SERVER_CLUSTER_SEED_URLS=${DLLM_SERVER_CLUSTER_SEED_URLS}
DLLM_SERVER_CORS_ALLOW_ORIGINS=${DLLM_SERVER_CORS_ALLOW_ORIGINS}
DLLM_SERVER_CORS_ALLOW_CREDENTIALS=${DLLM_SERVER_CORS_ALLOW_CREDENTIALS}
DLLM_SERVER_DISPATCH_INTERVAL_SEC=${DLLM_SERVER_DISPATCH_INTERVAL_SEC}
DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO=${DLLM_SERVER_SCHEDULER_SPEED_TOLERANCE_RATIO}
DLLM_SERVER_PORT=${DLLM_SERVER_PORT}
NODE_IP=${NODE_IP}
NODE_INTERNAL_IP=${NODE_INTERNAL_IP}
DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}
DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}
DOCKER_WEB_CONTAINER_NAME=${DOCKER_WEB_CONTAINER_NAME}
DLLM_WEB_PORT=${DLLM_WEB_PORT}
VITE_API_BASE=${VITE_API_BASE}
VITE_PROXY_TARGET=${VITE_PROXY_TARGET}
VITE_API_KEY=${VITE_API_KEY}
VITE_USE_MOCK=${VITE_USE_MOCK}
EOF

mkdir -p "${ROOT_DIR}/data/server"

if docker compose version >/dev/null 2>&1; then
  docker compose --env-file "${ENV_FILE}" -f docker-compose.server.yml up -d --build
else
  docker-compose --env-file "${ENV_FILE}" -f docker-compose.server.yml up -d --build
fi

echo "Deploy complete."
echo "Node ID: ${NODE_ID}"
echo "Internal token persisted at ${ENV_FILE}"
echo ""
echo "=== Deployment Config Summary ==="
echo "ENV_FILE: ${ENV_FILE}"
echo "Server:"
echo "  image=${DOCKER_IMAGE_NAME}"
echo "  container=${DOCKER_CONTAINER_NAME}"
echo "  host_port=${DLLM_SERVER_PORT}"
echo "  cluster_enabled=${DLLM_SERVER_CLUSTER_ENABLED}"
echo "  cluster_self_url=${DLLM_SERVER_CLUSTER_SELF_URL}"
echo "  cluster_seed_urls=${DLLM_SERVER_CLUSTER_SEED_URLS}"
echo "  db_url=${DLLM_SERVER_DB_URL}"
echo "Web:"
echo "  container=${DOCKER_WEB_CONTAINER_NAME}"
echo "  host_port=${DLLM_WEB_PORT}"
echo "  vite_api_base=${VITE_API_BASE}"
echo "  vite_proxy_target=${VITE_PROXY_TARGET}"
echo "  vite_use_mock=${VITE_USE_MOCK}"
echo "Network/CORS:"
echo "  node_ip=${NODE_IP}"
echo "  node_internal_ip=${NODE_INTERNAL_IP}"
echo "  cors_allow_origins=${DLLM_SERVER_CORS_ALLOW_ORIGINS}"
echo "  cors_allow_credentials=${DLLM_SERVER_CORS_ALLOW_CREDENTIALS}"
echo "Auth:"
echo "  api_keys_bootstrap=${DLLM_SERVER_API_KEYS_BOOTSTRAP}"
echo "  internal_token=${INTERNAL_TOKEN}"
echo "  vite_api_key=${VITE_API_KEY}"
echo "Access URLs:"
echo "  server_health=http://127.0.0.1:${DLLM_SERVER_PORT}/health"
echo "  web=http://127.0.0.1:${DLLM_WEB_PORT}"
